#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xfx.Controls.Droid.Resource", IsApplication=false)]

namespace Xfx.Controls.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public static int PrimaryDarkBlue = 2130903040;
			
			// aapt resource value: 0x7f030002
			public static int PrimaryLightBlue = 2130903042;
			
			// aapt resource value: 0x7f030001
			public static int PrimaryMediumBlue = 2130903041;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public static int autoCompleteTextInputLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int autoCompleteTextView = 2130968577;
			
			// aapt resource value: 0x7f040003
			public static int textInputEdit = 2130968579;
			
			// aapt resource value: 0x7f040002
			public static int textInputLayout = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int AutoCompleteTextInputLayout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int TextInputLayout = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
